### ISSUE TITLE
ETH_CALL doesn't respect past block numbers correctly

### ISSUE THREAD

**Issue by iamdoron** [trufflesuite/ganache-core#54]
when running ETH_CALL there is an option to provide a block number (QUANTITY) (https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_call). It seems like ganache always returns the call on the 'latest' block - it should at least throw if this option is not supported.

## Steps to Reproduce
add this to requests.js : 
```javascript
    it("should call a method on a past block (eth_call)", function(done){
      var exampleOutput = solc.compile(source).contracts[":Example"]
      web3.eth.contract(JSON.parse(exampleOutput.interface)).new({ data: exampleOutput.bytecode, from: accounts[0], gas: 3141592 }, function(err, example){
        if(err) return done(err)
        if(!example.address) return
        example.setValue(26, {from: accounts[0], gas: 3141592}, function(err, tx) {
          if (err) return done(err);
          web3.eth.getBlock('latest', false, function(err, blockAfterSet26){
            if (err) return done(err);
            example.setValue(30, {from: accounts[0], gas: 3141592}, function(err, tx) {
              if (err) return done(err);
              example.value.call(blockAfterSet26.number, function(err, value) {
                if (err) return done(err)
                assert.equal(value.toNumber(), 26);
                done()
              })
            })
          })
        })
      })
    })
```

returns:
```
Uncaught AssertionError [ERR_ASSERTION]: 30 == 26
```
## Context
I was trying to test a code that uses this ETH_CALL feature and the test failed

## Your Environment

* Version used: 2.0.2
* Operating System and version: macOs  10.13.2

**Comment by benjamincburns** [comment]
Hi @iamdoron - thanks for reporting this. Fortunately, this is fixed in our `develop` branch. I'm just in the process of pushing out a beta (`v3.0.0-beta.0`) release which will contain that fix, amongst many other important changes.

In the mean time this issue was already reported over on trufflesuite/ganache#204. I'd recommend subscribing to that issue and reopening that one should the soon-to-be-published beta build not fix your problem.

**Comment by iamdoron** [comment]
Hi,
Thanks for the quick response
I ran the following test (you can add it to test/requests.js), and it's still failing:

```javascript
  it("should call a method on a past block (eth_call)", function(done){
      var exampleOutput = solc.compile(source).contracts[":Example"]
      var contract = new web3.eth.Contract(JSON.parse(exampleOutput.interface))
      contract.deploy({ data: exampleOutput.bytecode }).send({ from: accounts[0], gas: 3141592 }).then(function(example){
        // TODO: ugly workaround - not sure why this is necessary.
        if (!example._requestManager.provider) {
          example._requestManager.setProvider(web3.eth._provider);
        }
        return example.methods.setValue(26).send({from: accounts[0], gas: 3141592}).then(function(tx) {
          return web3.eth.getBlock('latest', false).then(function(blockAfterSet26){
            return example.methods.setValue(30).send({from: accounts[0], gas: 3141592}).then(function(tx) {
              return example.methods.value().call(blockAfterSet26.number).then(function(value) {
                assert.equal(Number(value), 26);
                done()
              })
            })
          })
        })
      }).catch(done)
    })
```

I ran it on commit the latest develop  (commit df605cb1f3abd95f70ac6291c49a97ec58fb692b):
```
AssertionError [ERR_ASSERTION]: 30 == 26
```

**Comment by benjamincburns** [comment]
Apologies, I misunderstood the original issue -- and thanks for the test! The problem you're reporting is already captured in trufflesuite/ganache-cli#249. Can you please track this issue for updates?
